---
title: "Control calidad - Base mensual"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pointblank)
library(tidyr)
library(dplyr)

# Using `validate_rmd()` here to enable validation mode for R Markdown
# documents; options for the can be set here, as well
validate_rmd()
```


```{r small_table}
df_transparencia_orig <- readxl::read_excel("bases/V. FINAL Formulario de relevamiento - Índice de Transparencia 2024 (respuestas)_v2.xlsx")
```

If all validations in a `validate` chunk do not fail, we can still inspect the validation code.

```{r}
df_transparencia <- df_transparencia_orig |> 
  relocate("El organismo relevado pertenece a:", .after = "Administración central y desconcentrada") |> 
  pivot_longer(cols = 9:(ncol(df_transparencia_orig) - 3), 
               names_to = "pregunta", values_to = "respuesta")
```

Corremos una serie de validaciones sobre la base de trabajo, previo a ejecutar el flujo de trabajo para el procesamiento del índice

```{r validate = TRUE}
variables <- c("Marca temporal", "Período", "Tipo de organismo", "Universidades:", 
               "Empresas y Entes del Sector Público Nacional", "Organismos descentralizados",
               "Administración central y desconcentrada", "El organismo relevado pertenece a:",
               "Link del sitio web", "Nombre y apellido de quien relevó", "Fecha del relevamiento",
               "pregunta", "respuesta")

agente <- create_agent(tbl = df_transparencia) %>%
  col_exists(columns = all_of(variables)) %>% # this passes validation
  #col_is_posix("Marca temporal") %>%
  col_vals_in_set(columns = respuesta, set = c("Si", "Actualizado", "Actualizada", "Parcialmente", "No",
                                               "Desactualizado", "Desactualizada", "No corresponde", "Valor nulo",
                                               NA), 
                  label = "Chequeo categorías disponibles ") |> 
  interrogate()
  
  agente
```
